apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crawlers
  name: crawlers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawlers
  template:
    metadata:
      labels:
        app: crawlers
    spec:
      containers:
      - image: 637423341870.dkr.ecr.ap-northeast-2.amazonaws.com/crawlers:latest
        name: crawlers
        env:
          - name: HTTP_PORT
            value: '8021'
          - name: TARGET_COMPANIES
            value: 'toss inflearn'
          - name: TOSS_BASE_URI
            value: 'https://toss.tech'
          - name: INFLEARN_BASE_URI
            value: 'https://tech.inflab.com/posts'
          - name: DOCS_GRPC_URL
            value: 'docs:5001'
        ports:
          - containerPort: 8021

