apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docs
  name: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - image: 637423341870.dkr.ecr.ap-northeast-2.amazonaws.com/docs:latest
        name: docs
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString
          - name: HTTP_PORT
            value: '8011'
          - name: DOCS_GRPC_URL
            value: 'docs:5001'
        ports:
          - containerPort: 8011
          - containerPort: 8012


