apiVersion: v1
kind: Service
metadata:
  labels:
    app: docs
  name: docs
spec:
  ports:
  - name: "tcp"
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: docs
  type: ClusterIP
